export const els = {
  lessonList: document.getElementById("lessonList"),
  lessonCountBadge: document.getElementById("lessonCountBadge"),
  loadStatus: document.getElementById("loadStatus"),
  contentPanel: document.querySelector(".content-panel"),
  lessonEmpty: document.getElementById("lessonEmpty"),
  lessonDetail: document.getElementById("lessonDetail"),
  lessonTitle: document.getElementById("lessonTitle"),
  lessonMeta: document.getElementById("lessonMeta"),
  tabButtons: Array.from(document.querySelectorAll(".tab-btn")),
  tabVocab: document.getElementById("tabVocab"),
  tabPinyin: document.getElementById("tabPinyin"),
  tabGrammar: document.getElementById("tabGrammar"),
  tabTests: document.getElementById("tabTests"),
  lesson0Link: document.getElementById("lesson0Link"),
  wordModal: document.getElementById("wordModal"),
  wordModalCloseBtn: document.getElementById("wordModalCloseBtn"),
  wordModalContent: document.getElementById("wordModalContent"),
  prevWordBtn: document.getElementById("prevWordBtn"),
  nextWordBtn: document.getElementById("nextWordBtn"),
};
